name: node
version: '22.0.0-nightly20240318454d0806'
summary: Node.js
description: |
  A JavaScript runtime built on Chrome's V8 JavaScript engine. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient. Node.js' package ecosystem, npm, is the largest ecosystem of open source libraries in the world. https://nodejs.org/

grade: stable
confinement: classic
base: core22

apps:
  node:
    command: bin/node
  npm:
    command: bin/npm
  npx:
    command: bin/npx
  yarn:
    command: bin/yarn.js
  yarnpkg:
    command: bin/yarn.js

parts:
  gcc-10:
    plugin: nil
    override-pull: 'true'
    override-build: |
      sudo apt --yes install software-properties-common
      sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
      sudo apt --yes install gcc-10 g++-10 python3-distutils
    override-stage: 'true'
    override-prime: 'true'
  node:
    plugin: make
    source-type: tar
    source: https://nodejs.org/download/nightly/v22.0.0-nightly20240318454d0806a1/node-v22.0.0-nightly20240318454d0806a1.tar.gz
    make-parameters:
      - V=
    override-build: |
      export CC="gcc-10"
      export CXX="g++-10"
      export LINK="g++-10"
      export V=
      ./configure --verbose --prefix=/ --release-urlbase=https://nodejs.org/download/nightly/ --tag=nightly20240318454d0806a1
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/etc
      echo "prefix = /usr/local" >> $SNAPCRAFT_PART_INSTALL/etc/npmrc
  yarn:
    source-type: tar
    source: https://yarnpkg.com/latest.tar.gz
    plugin: dump
    # Yarn has a problem with lifecycle scripts when used inside snap, they don't complete properly, with exit code !=0.
    # Replacing the spinner with proper stdio appears to fix it.
    override-build: |
      snapcraftctl build
      chmod -R g-s $SNAPCRAFT_PART_INSTALL
      sed -i "s/var stdio = spinner ? undefined : 'inherit';/var stdio = 'inherit';/" $SNAPCRAFT_PART_INSTALL/lib/cli.js
