name: node
version: '26.5.0'
summary: Node.js
description: |
  A JavaScript runtime built on Chrome's V8 JavaScript engine. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient. Node.js' package ecosystem, npm, is the largest ecosystem of open source libraries in the world. https://nodejs.org/

grade: stable
confinement: classic
base: core24

apps:
  node:
    command: bin/node
  npm:
    command: bin/npm
  npx:
    command: bin/npx

parts:
  node:
    plugin: make
    source-type: tar
    source: https://nodejs.org/download/release/v26.5.0/node-v26.5.0.tar.gz
    build-snaps:
      - rustup/latest/stable
    build-packages:
      # Ensure these and the build environment below match the minimum GCC and G++ versions for this Node release.
      # https://github.com/nodejs/node/blob/main/BUILDING.md#building-nodejs-on-supported-platforms
      - gcc-14
      - g++-14
    stage-packages:
      # Include C++ runtime libraries that Node.js needs
      - libstdc++6
      - libgcc-s1
    build-environment:
      - CC: gcc-14
      - CXX: g++-14
      - LINK: g++-14
      - RUSTUP_TOOLCHAIN: "1.83.0"
      - V: ""
    make-parameters:
      - V=
      - LDFLAGS=-Wl,-rpath=/snap/node/current/lib/$(SNAPCRAFT_ARCH_TRIPLET):/snap/node/current/usr/lib/$(SNAPCRAFT_ARCH_TRIPLET):/snap/core24/current/lib/$(SNAPCRAFT_ARCH_TRIPLET):/snap/core24/current/usr/lib/$(SNAPCRAFT_ARCH_TRIPLET)
    override-build: |
      rustup toolchain install "$RUSTUP_TOOLCHAIN" --profile minimal
      ./configure --verbose --prefix=/ --release-urlbase=https://nodejs.org/download/release/ --tag= --v8-enable-temporal-support
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/etc
      echo "prefix = /usr/local" >> $CRAFT_PART_INSTALL/etc/npmrc
