name: node
version: '25.0.0-nightly202509108ec29f24'
summary: Node.js
description: |
  A JavaScript runtime built on Chrome's V8 JavaScript engine. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient. Node.js' package ecosystem, npm, is the largest ecosystem of open source libraries in the world. https://nodejs.org/

grade: stable
confinement: classic
base: core24

apps:
  node:
    command: bin/node
  npm:
    command: bin/npm
  npx:
    command: bin/npx
  yarn:
    command: bin/yarn.js
  yarnpkg:
    command: bin/yarn.js

parts:
  node:
    plugin: make
    source-type: tar
    source: https://nodejs.org/download/nightly/v25.0.0-nightly202509108ec29f24fc/node-v25.0.0-nightly202509108ec29f24fc.tar.gz
    build-packages:
      # Ensure these and the build environment below match the minimum GCC and G++ versions for this Node release.
      # https://github.com/nodejs/node/blob/main/BUILDING.md#building-nodejs-on-supported-platforms
      - gcc-14
      - g++-14
    stage-packages:
      # Include C++ runtime libraries that Node.js needs
      - libstdc++6
      - libgcc-s1
    build-environment:
      - CC: gcc-14
      - CXX: g++-14
      - LINK: g++-14
      - V: ""
    make-parameters:
      - V=
      - LDFLAGS=-Wl,-dynamic-linker=/snap/core24/current/lib64/ld-linux-x86-64.so.2 -Wl,-rpath=/snap/node/current/lib/x86_64-linux-gnu:/snap/node/current/usr/lib/x86_64-linux-gnu:/snap/core24/current/lib/x86_64-linux-gnu:/snap/core24/current/usr/lib/x86_64-linux-gnu
    override-build: |
      ./configure --verbose --prefix=/ --release-urlbase=https://nodejs.org/download/nightly/ --tag=nightly202509108ec29f24fc
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/etc
      echo "prefix = /usr/local" >> $CRAFT_PART_INSTALL/etc/npmrc
  yarn:
    source-type: tar
    source: https://yarnpkg.com/latest.tar.gz
    plugin: dump
    # Yarn has a problem with lifecycle scripts when used inside snap, they don't complete properly, with exit code !=0.
    # Replacing the spinner with proper stdio appears to fix it.
    override-build: |
      craftctl default
      chmod -R g-s $CRAFT_PART_INSTALL
      sed -i "s/var stdio = spinner ? undefined : 'inherit';/var stdio = 'inherit';/" $CRAFT_PART_INSTALL/lib/cli.js
