name: 
on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build:
    if: | 
      github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    env:
      BRANCH_NAME: ${{ github.head.ref }}


    steps:
      - name: echo branch name
        run: |
          echo ${{ github.head_ref }}
          feature_name=$(echo "${{ env.BRANCH_NAME}}" | cut -d "-" -f 3)
          echo "$feature_name"
      
      
