name: 
on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build:
    if: | 
      github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    env:
      BRANCH_NAME: ${{ github.head_ref }}


    steps:
      - name: echo branch name
        id: branch
        run: |
          # echo ${{ github.head_ref }}
          feature_name=$(echo ${{ env.BRANCH_NAME }} | cut -d "-" -f 3)
          echo "$feature_name"
      
      
      - name: echo etc
        run: |
          echo "branch name is ${{ steps.branch.outputs.feature_name }}"
         
      
