name: 
on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build:
    if: | 
      github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    


    steps:
      - name: echo branch name
        run: |
          echo "${{ github_head_ref }}      
      
      
      
