name: 
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      BRANCH_NAME: ${{ github.head_ref }}
      
    steps:
      - name: echo branch name
        id: branch
        run: |
          echo ${{ github.head_ref }}    
